/*
	Trigger to increase class size in CLASSES table on insertion of ENROLLMENTS table entry
*/
CREATE OR REPLACE TRIGGER TRIG_ON_INS_ENROLL_UPD_CLASSES
  AFTER INSERT ON ENROLLMENTS
  FOR EACH ROW
BEGIN
  UPDATE CLASSES
     SET CLASS_SIZE = CLASS_SIZE + 1
   WHERE CLASSID = :NEW.CLASSID;
END;
/
