/*
	Trigger to make TA column entry NULL in CLASSES table on deletion of TA table entry
*/
CREATE OR REPLACE TRIGGER TRIG_ON_DEL_TAS_UPD_CLASSES
  BEFORE DELETE ON TAS
  FOR EACH ROW
DECLARE
  CURSOR C1 IS
    SELECT CLASSID FROM CLASSES WHERE UPPER(TA_B#) = UPPER(:OLD.B#);
  L_TA_CNT NUMBER;
BEGIN
  FOR C1_REC IN C1 LOOP
    UPDATE CLASSES SET TA_B# = NULL WHERE CLASSID = C1_REC.CLASSID;
  END LOOP;
END;
/
