/*
	Trigger to delete TA table entry on deletion of STUDENT table entry
*/
CREATE OR REPLACE TRIGGER TRIG_ON_DEL_STUDENTS_DEL_TA
  BEFORE DELETE ON STUDENTS
  FOR EACH ROW
DECLARE
  CURSOR C1 IS
    SELECT COUNT(1) FROM TAS WHERE UPPER(B#) = UPPER(:OLD.B#);
  L_TA_CNT NUMBER;
BEGIN
  OPEN C1;
  FETCH C1
    INTO L_TA_CNT;
  CLOSE C1;

  IF L_TA_CNT = 1 THEN
    DELETE FROM TAS WHERE UPPER(B#) = UPPER(:OLD.B#);
  END IF;
END;
/
